### ISSUE TITLE
invalid value encountered in arcsin: compute_lo

### ISSUE THREAD

**Issue by SkirOwen** [louis-etne/Orbital-Sp423#2]
RuntimeWarning: invalid value encountered in arcsin
  return np.rad2deg(correction) + factor * np.rad2deg(np.arcsin(np.tan(np.deg2rad(la)) / np.tan(np.deg2rad(inclinaison))))

Valeur _au hasard_, peut-être pour ça, mais vieux être prudent :)

Nombre de chiffre après la virgule : 10
[Demi-grand axe (km)] a = 80066
[Excentricité] e = 0.12
[Inclinaison (deg)] i = 52
[Argument du périgé (deg)] w = 120
[Longitude du noeud ascendant (deg)] L_omega = 260

-60 -30 0 +30 +60 +90 +120 +150 +180

**Comment by louis-etne** [comment]
Une longitude est généralement comprise entre -180 et 180 dégrées. Je t’invite à corriger ton paramètre et à soumettre une nouvelle issue si le problème se présente de nouveau 😉
